kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ibm-iscsi-agent
spec:
  selector:
    matchLabels:
      name: ibm-iscsi-agent
  template:
    metadata:
      labels:
        name: ibm-iscsi-agent
    spec:
      hostNetwork: true
      containers:
      - name: iscsi-agent
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
        image: "{{ .Values.iscsiAgent.image.repository }}:{{ .Values.iscsiAgent.image.tag }}"
        imagePullPolicy: {{ .Values.iscsiAgent.image.pullPolicy }}
        env:
        - name: ADDRESS
          value: {{ .Values.iscsiAgent.address }}
        ports:
        - name: iscsi
		  containerPort: {{ .Values.iscsiAgent.port }}
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /sys
          name: sysfs
        - mountPath: /dev
          name: dev
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: sysfs
        hostPath:
          path: /sys
          type: Directory
      - name: dev
        hostPath:
          path: /dev
          type: Directory
