apiVersion: csi.ibm.com/v1
kind: IBMBlockCSI
metadata:
  name: ibm-block-csi
  namespace: kube-system
  labels:
    app.kubernetes.io/name: ibm-block-csi-operator
    app.kubernetes.io/instance: ibm-block-csi-operator
    app.kubernetes.io/managed-by: ibm-block-csi-operator
spec:
  # controller is a statefulSet with ibm-block-csi-driver-controller
  # container and csi-provisioner, csi-attacher and livenessprobe sidecars.
  controller:
    repository: stg-artifactory.haifa.ibm.com:5030/ibm-block-csi-driver-controller-s390x
    tag: "latest"
    imagePullPolicy: IfNotPresent
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - s390x

  # node is a daemonSet with ibm-block-csi-driver-node container
  # and csi-node-driver-registrar and livenessprobe sidecars.
  node:
    repository: stg-artifactory.haifa.ibm.com:5030/ibm-block-csi-driver-node-s390x
    tag: "1.1.0_b03_CSI_1088"
    imagePullPolicy: IfNotPresent
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - s390x

#    tolerations:
#    - effect: NoSchedule
#      key: node-role.kubernetes.io/master
#      operator: Exists

  sidecars:
  - name: csi-node-driver-registrar
    repository: registry.redhat.io/openshift4/ose-csi-driver-registrar
    tag: "latest"
    imagePullPolicy: IfNotPresent
  - name: csi-provisioner
    repository: registry.redhat.io/openshift4/ose-csi-external-provisioner-rhel7
    tag: "latest"
    imagePullPolicy: IfNotPresent
  - name: csi-attacher
    repository: registry.redhat.io/openshift4/ose-csi-external-attacher
    tag: "latest"
    imagePullPolicy: IfNotPresent
  - name: livenessprobe
    repository: registry.redhat.io/openshift4/ose-csi-livenessprobe
    tag: "latest"
    imagePullPolicy: IfNotPresent

#  imagePullSecrets:
#  - "secretName"
