apiVersion: csi.ibm.com/v1
kind: IBMBlockCSI
metadata:
  name: ibm-block-csi
  namespace: kube-system
  labels:
    app.kubernetes.io/name: ibm-block-csi-operator
    app.kubernetes.io/instance: ibm-block-csi-operator
    app.kubernetes.io/managed-by: ibm-block-csi-operator
spec:
  controller:
    repository: ibmcom/ibm-block-csi-driver-controller
    tag: "1.0.0"
  node:
    repository: ibmcom/ibm-block-csi-driver-node
    tag: "1.0.0"
  sidecars:
  - name: csi-node-driver-registrar
    repository: quay.io/k8scsi/csi-node-driver-registrar
    tag: "v1.2.0"
  - name: csi-provisioner
    repository: quay.io/k8scsi/csi-provisioner
    tag: "v1.3.0"
  - name: csi-attacher
    repository: quay.io/k8scsi/csi-attacher
    tag: "v1.2.1"
  - name: livenessprobe
    repository: quay.io/k8scsi/livenessprobe
    tag: "v1.1.0"
