apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ibmblockcsis.csi.ibm.com
spec:
  group: csi.ibm.com
  names:
    kind: IBMBlockCSI
    listKind: IBMBlockCSIList
    plural: ibmblockcsis
    singular: ibmblockcsi
    shortNames:
    - ibc
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            controller:
              properties:
                repository:
                  description: The repository of the controller image
                  type: string
                tag:
                  description: The tag of the controller image
                  type: string
              required:
              - repository
              - tag
              type: object
            node:
              properties:
                repository:
                  description: The repository of the node image
                  type: string
                tag:
                  description: The tag of the node image
                  type: string
              required:
              - repository
              - tag
              type: object
          required:
          - controller
          - node
          type: object
        status:
          properties:
            controllerReady:
              type: boolean
            nodeReady:
              type: boolean
            phase:
              description: Phase is the driver running phase
              type: string
            version:
              description: Version is the current driver version
              type: string
          required:
          - phase
          - controllerReady
          - nodeReady
          - version
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
