apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configs.csi.ibm.com
spec:
  group: csi.ibm.com
  names:
    kind: Config
    listKind: ConfigList
    plural: configs
    singular: config
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            defineHost:
              type: boolean
            nodeAgent:
              properties:
                port:
                  description: The port of the node agent server
                  type: string
                repository:
                  description: The repository of the node agent image
                  type: string
                tag:
                  description: The tag of the node agent image
                  type: string
              required:
              - repository
              - tag
              - port
              type: object
          required:
          - defineHost
          - nodeAgent
          type: object
        status:
          properties:
            nodeAgent:
              description: Phase is the driver running phase
              properties:
                phase:
                  description: Phase is the NodeAgent running phase
                  type: string
              required:
              - phase
              type: object
          required:
          - nodeAgent
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
