apiVersion: csi.ibm.com/v1
kind: IBMBlockCSI
metadata:
  name: ibm-block-csi
  namespace: kube-system
spec:
  controller:
    repository: stg-artifactory.haifa.ibm.com:5030/ibm-block-csi-controller-driver
    tag: "1.0.0_b35_origin.develop"
  node:
    repository: stg-artifactory.haifa.ibm.com:5030/ibm-block-csi-node-driver
    tag: "1.0.0_b35_origin.develop"
