apiVersion: storage.k8s.io/v1beta1   ## for k8s 1.13 it should be csi.storage.k8s.io/v1alpha1 and requires to set feature gate --feature-gates=CSIDriverRegistry=true
kind: CSIDriver
metadata:
  name: ibm-block-csi-driver
spec:
  attachRequired: true
  podInfoOnMount: false