kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ibm-node-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ibm-node-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ibm-node-agent
    spec:
      hostNetwork: true
      containers:
      - name: node-agent
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
        image: stg-artifactory.haifa.ibm.com:5030/ibm-node-agent:0.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: ADDRESS
          value: :10086
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: grpc
          containerPort: 10086
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /sys
          name: sysfs
        - mountPath: /dev
          name: dev
        - name: iscsi
          mountPath: /etc/iscsi
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: sysfs
        hostPath:
          path: /sys
          type: Directory
      - name: dev
        hostPath:
          path: /dev
          type: Directory
      - name: iscsi
        hostPath:
          path: /etc/iscsi
          type: DirectoryOrCreate
