apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ibm-node-collector
rules:
- apiGroups:
  - csi.ibm.com
  resources:
  - nodeinfos
  verbs:
  - get
  - create
  - update
