apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-block-csi-driver-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-block-csi-driver-operator
  template:
    metadata:
      labels:
        name: ibm-block-csi-driver-operator
    spec:
      serviceAccountName: ibm-block-csi-driver-operator
      containers:
        - name: ibm-block-csi-driver-operator
          image: stg-artifactory.haifa.ibm.com:5030/ibm-block-csi-driver-operator:0.0.5
          imagePullPolicy: IfNotPresent
          command:
          - ibm-block-csi-driver-operator
          env:
            - name: WATCH_NAMESPACE
              value: ""
              #valueFrom:
              #  fieldRef:
              #    fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-block-csi-driver-operator"
