apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-block-csi-driver-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-block-csi-driver-operator
  template:
    metadata:
      labels:
        name: ibm-block-csi-driver-operator
    spec:
      serviceAccountName: ibm-block-csi-driver-operator
      containers:
        - name: ibm-block-csi-driver-operator
          image: stg-artifactory.haifa.ibm.com:5030/ibm-block-csi-driver-operator:0.0.6
          imagePullPolicy: IfNotPresent
          command:
          - ibm-block-csi-driver-operator
          env:
            - name: WATCH_NAMESPACE
              value: ""
              #valueFrom:
              #  fieldRef:
              #    fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-block-csi-driver-operator"
            - name: ENDPOINT
              value: "unix:///storage/storage.sock:10086"
            - name: ISCSI_AGENT_PORT
              value: "10086"
          volumeMounts:
            - name: socket-dir
              mountPath: /storage/
        - name: ibm-storage-agent
          image: stg-artifactory.haifa.ibm.com:5030/ibm-storage-agent:v0.0.3
          imagePullPolicy: IfNotPresent
          env:
            - name: ENDPOINT
              value: "unix:///storage/storage.sock:10086"
          volumeMounts:
            - name: socket-dir
              mountPath: /storage/

      volumes:
        - name: socket-dir
          emptyDir: {}
