nodeAgent:
  image:
    repository: stg-artifactory.haifa.ibm.com:5030/ibm-node-agent
    tag: "0.0.1"
    pullPolicy: IfNotPresent
  address: ":10086"
  port: 10086

operator:
  image:
    repository: stg-artifactory.haifa.ibm.com:5030/ibm-block-csi-driver-operator
    tag: "0.0.7"
    pullPolicy: IfNotPresent
  endpoint: "unix:///storage/storage.sock:10086"
  enableHostDefine: "no"

storageAgent:
  image:
    repository: stg-artifactory.haifa.ibm.com:5030/ibm-storage-agent
    tag: "v0.0.3"
    pullPolicy: IfNotPresent